"use client";

import * as React from "react";
import { useSearchParams, useRouter } from "next/navigation";
import Link from "next/link";
import {
  Search,
  ArrowRight,
  Package,
  MapPin,
  Clock,
  Truck,
  CheckCircle2,
  AlertCircle,
  Phone,
  Share2,
  Printer,
  ShieldCheck,
  User,
  Copy,
  Check,
  Sparkles,
} from "lucide-react";
import { Button, buttonVariants } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";

interface WaypointEvent {
  id: string;
  status: string;
  location: string;
  timestamp: string;
  description: string;
  isCompleted: boolean;
  isCurrent: boolean;
}

interface ShipmentData {
  id: string;
  status: "IN_TRANSIT" | "OUT_FOR_DELIVERY" | "DELIVERED" | "BOOKED";
  statusLabel: string;
  service: string;
  originHub: string;
  destinationHub: string;
  recipientName: string;
  recipientCity: string;
  estimatedDelivery: string;
  weight: string;
  codAmount: string;
  paymentStatus: "PAID" | "COD_PENDING" | "COLLECTED";
  courierName?: string;
  courierPhone?: string;
  timeline: WaypointEvent[];
}

const mockShipments: Record<string, ShipmentData> = {
  "WP-DAC-98214": {
    id: "WP-DAC-98214",
    status: "IN_TRANSIT",
    statusLabel: "In Linehaul Transit",
    service: "Express Next-Day",
    originHub: "Dhaka Central Gateway (HUB-DAC-01)",
    destinationHub: "Chittagong Port Terminal (HUB-CTG-01)",
    recipientName: "Sabbir Ahmed",
    recipientCity: "Agrabad, Chittagong",
    estimatedDelivery: "Tomorrow by 2:30 PM",
    weight: "1.8 kg",
    codAmount: "৳2,450",
    paymentStatus: "COD_PENDING",
    courierName: "Mahbub Alam (Highway Fleet)",
    courierPhone: "+880-1712-349812",
    timeline: [
      {
        id: "1",
        status: "Consignment Manifested",
        location: "Dhaka Merchant Facility",
        timestamp: "Sep 22, 2026 - 10:15 AM",
        description: "Digital waypoint barcode generated by merchant.",
        isCompleted: true,
        isCurrent: false,
      },
      {
        id: "2",
        status: "Picked Up by Courier",
        location: "Tejgaon, Dhaka",
        timestamp: "Sep 22, 2026 - 01:45 PM",
        description: "Package received and scan-verified by first-mile rider.",
        isCompleted: true,
        isCurrent: false,
      },
      {
        id: "3",
        status: "Sorted at Central Hub",
        location: "Dhaka Central Gateway",
        timestamp: "Sep 22, 2026 - 06:20 PM",
        description: "Automated scan completed and routed for Chittagong linehaul.",
        isCompleted: true,
        isCurrent: false,
      },
      {
        id: "4",
        status: "In Highway Linehaul Transit",
        location: "Dhaka - Chittagong Expressway",
        timestamp: "Sep 22, 2026 - 09:30 PM",
        description: "Consignment moving overnight in sealed container vehicle CT-409.",
        isCompleted: false,
        isCurrent: true,
      },
      {
        id: "5",
        status: "Arrival at Distribution Hub",
        location: "Chittagong Port Terminal",
        timestamp: "Pending Arrival",
        description: "Scheduled intake and cross-docking for neighborhood dispatch.",
        isCompleted: false,
        isCurrent: false,
      },
      {
        id: "6",
        status: "Out for Last-Mile Delivery",
        location: "Agrabad Delivery Center",
        timestamp: "Pending Dispatch",
        description: "Package assigned to local rider with OTP verification.",
        isCompleted: false,
        isCurrent: false,
      },
      {
        id: "7",
        status: "Delivered & Verified",
        location: "Recipient Destination",
        timestamp: "Pending Handover",
        description: "Handed over to recipient with signature and COD clearance.",
        isCompleted: false,
        isCurrent: false,
      },
    ],
  },
  "WP-CTG-44102": {
    id: "WP-CTG-44102",
    status: "OUT_FOR_DELIVERY",
    statusLabel: "Out for Delivery",
    service: "Same-Day City Transit",
    originHub: "Uttara North Hub (HUB-DAC-03)",
    destinationHub: "Gulshan Hub (HUB-DAC-02)",
    recipientName: "Fatima Khanam",
    recipientCity: "Gulshan-2, Dhaka",
    estimatedDelivery: "Today by 6:00 PM",
    weight: "0.6 kg",
    codAmount: "৳0 (Prepaid)",
    paymentStatus: "PAID",
    courierName: "Rony Howlader (Rider #209)",
    courierPhone: "+880-1819-882190",
    timeline: [
      {
        id: "1",
        status: "Consignment Manifested",
        location: "Uttara Warehouse",
        timestamp: "Sep 22, 2026 - 11:00 AM",
        description: "Order booked for rush city delivery.",
        isCompleted: true,
        isCurrent: false,
      },
      {
        id: "2",
        status: "Picked Up by Courier",
        location: "Uttara Sector 7",
        timestamp: "Sep 22, 2026 - 12:15 PM",
        description: "Collected by same-day express rider.",
        isCompleted: true,
        isCurrent: false,
      },
      {
        id: "3",
        status: "Out for Last-Mile Delivery",
        location: "Gulshan-2 Circle",
        timestamp: "Sep 22, 2026 - 03:40 PM",
        description: "Rider is en route to delivery address.",
        isCompleted: false,
        isCurrent: true,
      },
      {
        id: "4",
        status: "Delivered & Verified",
        location: "Gulshan-2, Dhaka",
        timestamp: "Pending Handover",
        description: "Awaiting recipient OTP signature.",
        isCompleted: false,
        isCurrent: false,
      },
    ],
  },
  "WP-SYL-55201": {
    id: "WP-SYL-55201",
    status: "DELIVERED",
    statusLabel: "Successfully Delivered",
    service: "Express Next-Day",
    originHub: "Sylhet Express Hub (HUB-SYL-01)",
    destinationHub: "Dhaka Central Gateway (HUB-DAC-01)",
    recipientName: "Imtiaz Hossain",
    recipientCity: "Dhanmondi, Dhaka",
    estimatedDelivery: "Delivered on Sep 21",
    weight: "3.2 kg",
    codAmount: "৳4,100",
    paymentStatus: "COLLECTED",
    courierName: "Kamrul Hasan",
    courierPhone: "+880-1912-771122",
    timeline: [
      {
        id: "1",
        status: "Consignment Manifested",
        location: "Sylhet Zindabazar",
        timestamp: "Sep 20, 2026 - 02:00 PM",
        description: "Created by tea plantation merchant.",
        isCompleted: true,
        isCurrent: false,
      },
      {
        id: "2",
        status: "Hub Intake & Linehaul",
        location: "Sylhet Express Hub",
        timestamp: "Sep 20, 2026 - 07:15 PM",
        description: "Transferred via Dhaka highway linehaul container.",
        isCompleted: true,
        isCurrent: false,
      },
      {
        id: "3",
        status: "Out for Delivery",
        location: "Dhanmondi Hub",
        timestamp: "Sep 21, 2026 - 10:00 AM",
        description: "Handed to courier Kamrul Hasan for drop-off.",
        isCompleted: true,
        isCurrent: false,
      },
      {
        id: "4",
        status: "Delivered & OTP Verified",
        location: "Dhanmondi 27, Dhaka",
        timestamp: "Sep 21, 2026 - 01:25 PM",
        description: "Package received by Imtiaz Hossain. COD ৳4,100 collected.",
        isCompleted: true,
        isCurrent: true,
      },
    ],
  },
};

export function TrackingClient() {
  const searchParams = useSearchParams();
  const router = useRouter();

  const idFromUrl = searchParams.get("id") || "";
  const [query, setQuery] = React.useState(idFromUrl);
  const [activeShipmentId, setActiveShipmentId] = React.useState<string>(
    idFromUrl && mockShipments[idFromUrl.toUpperCase()]
      ? idFromUrl.toUpperCase()
      : "WP-DAC-98214"
  );
  const [copied, setCopied] = React.useState(false);

  React.useEffect(() => {
    if (idFromUrl) {
      setQuery(idFromUrl);
      if (mockShipments[idFromUrl.toUpperCase()]) {
        setActiveShipmentId(idFromUrl.toUpperCase());
      }
    }
  }, [idFromUrl]);

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    const clean = query.trim().toUpperCase();
    if (!clean) return;
    router.push(`/tracking?id=${encodeURIComponent(clean)}`);
    if (mockShipments[clean]) {
      setActiveShipmentId(clean);
    }
  };

  const handleSampleClick = (sampleId: string) => {
    setQuery(sampleId);
    router.push(`/tracking?id=${sampleId}`);
    setActiveShipmentId(sampleId);
  };

  const currentShipment = mockShipments[activeShipmentId];

  const handleCopyLink = () => {
    if (typeof window !== "undefined") {
      navigator.clipboard.writeText(window.location.href);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div className="space-y-10">
      {/* Search Bar Section */}
      <div className="mx-auto max-w-2xl text-center space-y-4">
        <form onSubmit={handleSearch} className="relative flex items-center">
          <div className="relative w-full">
            <Search className="pointer-events-none absolute left-4 top-3.5 size-5 text-muted-foreground" />
            <input
              type="text"
              placeholder="Enter Waypoint Tracking ID (e.g. WP-DAC-98214)"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              className="h-12 w-full rounded-2xl border border-border/80 bg-card/90 pl-11 pr-28 text-sm text-foreground placeholder:text-muted-foreground shadow-sm focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20 backdrop-blur-md"
            />
            <Button
              type="submit"
              size="sm"
              className="absolute right-2 top-2 rounded-xl h-8 px-4 text-xs font-semibold gap-1"
            >
              <span>Track</span>
              <ArrowRight className="size-3.5" />
            </Button>
          </div>
        </form>

        {/* Quick sample chips */}
        <div className="flex flex-wrap items-center justify-center gap-2 text-xs text-muted-foreground">
          <span>Try demo tracking IDs:</span>
          {Object.keys(mockShipments).map((id) => (
            <button
              key={id}
              type="button"
              onClick={() => handleSampleClick(id)}
              className={cn(
                "rounded-full border px-2.5 py-0.5 font-mono text-[11px] transition-all cursor-pointer",
                activeShipmentId === id
                  ? "border-primary bg-primary/10 text-primary font-bold shadow-xs"
                  : "border-border/80 bg-background/60 hover:text-foreground"
              )}
            >
              {id}
            </button>
          ))}
        </div>
      </div>

      {/* Shipment Details Result */}
      {currentShipment ? (
        <div className="space-y-8 animate-in fade-in duration-300">
          {/* Top Status Header Card */}
          <div className="rounded-3xl border border-border/80 bg-card p-6 sm:p-8 shadow-md backdrop-blur-md">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-6 border-b border-border/60">
              <div className="space-y-1">
                <div className="flex items-center gap-2.5">
                  <span className="font-mono text-xl sm:text-2xl font-black text-foreground">
                    {currentShipment.id}
                  </span>
                  <Badge
                    variant={
                      currentShipment.status === "DELIVERED"
                        ? "success"
                        : currentShipment.status === "OUT_FOR_DELIVERY"
                        ? "warning"
                        : "default"
                    }
                    className="text-xs"
                  >
                    {currentShipment.statusLabel}
                  </Badge>
                </div>
                <p className="text-xs text-muted-foreground">
                  Service Tier: <span className="font-semibold text-foreground">{currentShipment.service}</span>
                </p>
              </div>

              <div className="flex items-center gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={handleCopyLink}
                  className="rounded-xl text-xs gap-1.5 cursor-pointer"
                >
                  {copied ? <Check className="size-3.5 text-emerald-500" /> : <Copy className="size-3.5" />}
                  <span>{copied ? "Link Copied" : "Share"}</span>
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => window.print()}
                  className="rounded-xl text-xs gap-1.5 cursor-pointer"
                >
                  <Printer className="size-3.5" />
                  <span>Print</span>
                </Button>
              </div>
            </div>

            {/* Core Details Grid */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 pt-6">
              <div className="space-y-1">
                <span className="text-[11px] font-semibold text-muted-foreground uppercase tracking-wider">
                  Origin Hub
                </span>
                <p className="text-xs sm:text-sm font-semibold text-foreground flex items-center gap-1.5">
                  <MapPin className="size-3.5 text-primary shrink-0" />
                  <span className="truncate">{currentShipment.originHub}</span>
                </p>
              </div>

              <div className="space-y-1">
                <span className="text-[11px] font-semibold text-muted-foreground uppercase tracking-wider">
                  Destination
                </span>
                <p className="text-xs sm:text-sm font-semibold text-foreground flex items-center gap-1.5">
                  <MapPin className="size-3.5 text-emerald-500 shrink-0" />
                  <span className="truncate">{currentShipment.recipientCity}</span>
                </p>
              </div>

              <div className="space-y-1">
                <span className="text-[11px] font-semibold text-muted-foreground uppercase tracking-wider">
                  Estimated Delivery
                </span>
                <p className="text-xs sm:text-sm font-semibold text-primary flex items-center gap-1.5">
                  <Clock className="size-3.5 shrink-0" />
                  <span>{currentShipment.estimatedDelivery}</span>
                </p>
              </div>

              <div className="space-y-1">
                <span className="text-[11px] font-semibold text-muted-foreground uppercase tracking-wider">
                  Payment & COD
                </span>
                <p className="text-xs sm:text-sm font-semibold text-foreground">
                  {currentShipment.codAmount} ({currentShipment.paymentStatus.replace("_", " ")})
                </p>
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
            {/* Waypoint Timeline (8 cols) */}
            <div className="lg:col-span-8 rounded-3xl border border-border/80 bg-card p-6 sm:p-8 shadow-md">
              <h3 className="text-base font-bold text-foreground pb-6 border-b border-border/60 flex items-center gap-2">
                <ShieldCheck className="size-5 text-primary" />
                <span>Verified Waypoint Node Progression</span>
              </h3>

              <div className="mt-6 space-y-6 relative before:absolute before:left-3.5 before:top-3 before:bottom-3 before:w-0.5 before:bg-border">
                {currentShipment.timeline.map((event, idx) => (
                  <div key={event.id} className="relative pl-9 space-y-1.5">
                    <span
                      className={cn(
                        "absolute left-1.5 top-1.5 size-4 -translate-x-1/2 rounded-full border-2 transition-all",
                        event.isCurrent
                          ? "border-primary bg-primary ring-4 ring-primary/20 animate-pulse"
                          : event.isCompleted
                          ? "border-emerald-500 bg-emerald-500 text-white"
                          : "border-border bg-background"
                      )}
                    />
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1">
                      <div className="flex items-center gap-2">
                        <span className="text-sm font-bold text-foreground">
                          {event.status}
                        </span>
                        {event.isCurrent && (
                          <Badge variant="default" className="text-[10px] px-1.5 py-0">
                            Live Checkpoint
                          </Badge>
                        )}
                      </div>
                      <span className="text-[11px] font-mono text-muted-foreground">
                        {event.timestamp}
                      </span>
                    </div>

                    <p className="text-xs font-medium text-primary flex items-center gap-1">
                      <MapPin className="size-3" />
                      <span>{event.location}</span>
                    </p>
                    <p className="text-xs text-muted-foreground leading-relaxed">
                      {event.description}
                    </p>
                  </div>
                ))}
              </div>
            </div>

            {/* Courier Rider & Consignment Specs (4 cols) */}
            <div className="lg:col-span-4 space-y-6">
              {/* Rider Card */}
              {currentShipment.courierName && (
                <div className="rounded-3xl border border-border/80 bg-card p-6 shadow-xs space-y-4">
                  <span className="text-xs font-bold uppercase tracking-wider text-muted-foreground">
                    Assigned Courier
                  </span>
                  <div className="flex items-center gap-3">
                    <div className="flex size-12 items-center justify-center rounded-2xl bg-primary/10 text-primary">
                      <User className="size-6" />
                    </div>
                    <div>
                      <h4 className="text-sm font-bold text-foreground">
                        {currentShipment.courierName}
                      </h4>
                      <p className="text-xs text-muted-foreground">Waypoint Logistics Fleet</p>
                    </div>
                  </div>

                  {currentShipment.courierPhone && (
                    <a
                      href={`tel:${currentShipment.courierPhone}`}
                      className={cn(
                        buttonVariants({ variant: "outline", size: "sm" }),
                        "w-full rounded-xl text-xs gap-2 font-medium"
                      )}
                    >
                      <Phone className="size-3.5 text-primary" />
                      <span>{currentShipment.courierPhone}</span>
                    </a>
                  )}
                </div>
              )}

              {/* Consignment Attributes */}
              <div className="rounded-3xl border border-border/80 bg-muted/20 p-6 shadow-xs space-y-3">
                <span className="text-xs font-bold uppercase tracking-wider text-foreground">
                  Consignment Attributes
                </span>
                <div className="space-y-2 text-xs">
                  <div className="flex items-center justify-between text-muted-foreground">
                    <span>Declared Weight:</span>
                    <span className="font-semibold text-foreground font-mono">{currentShipment.weight}</span>
                  </div>
                  <div className="flex items-center justify-between text-muted-foreground">
                    <span>Recipient Name:</span>
                    <span className="font-semibold text-foreground">{currentShipment.recipientName}</span>
                  </div>
                  <div className="flex items-center justify-between text-muted-foreground">
                    <span>Handling Level:</span>
                    <span className="font-semibold text-foreground">Standard Fragile-Care</span>
                  </div>
                  <div className="flex items-center justify-between text-muted-foreground">
                    <span>Insurance:</span>
                    <span className="font-semibold text-emerald-600 dark:text-emerald-400">Verified TLS Covered</span>
                  </div>
                </div>
              </div>

              {/* Need Help Card */}
              <div className="rounded-3xl border border-primary/20 bg-primary/5 p-6 space-y-3">
                <h4 className="text-xs font-bold text-foreground flex items-center gap-1.5">
                  <AlertCircle className="size-4 text-primary" />
                  <span>Delay or Delivery Issue?</span>
                </h4>
                <p className="text-xs text-muted-foreground leading-relaxed">
                  Our dispatch operations center is available 24/7 to reroute, adjust delivery slots, or resolve handover delays.
                </p>
                <Link
                  href="/contact?type=tracking-support"
                  className="inline-flex items-center gap-1 text-xs font-semibold text-primary hover:underline"
                >
                  <span>Contact Dispatch Desk</span>
                  <ArrowRight className="size-3" />
                </Link>
              </div>
            </div>
          </div>
        </div>
      ) : (
        /* Empty / Not Found State */
        <div className="rounded-3xl border border-dashed border-border/80 bg-card/40 p-12 text-center space-y-4">
          <div className="mx-auto flex size-12 items-center justify-center rounded-2xl bg-muted text-muted-foreground">
            <Package className="size-6" />
          </div>
          <div className="space-y-1">
            <h3 className="text-base font-bold text-foreground">
              No Consignment Found for &quot;{query}&quot;
            </h3>
            <p className="text-xs text-muted-foreground max-w-md mx-auto">
              Please double-check the tracking ID printed on your merchant receipt or SMS alert.
              You can also test one of the demo tracking IDs above.
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
